name: "[internal] Slow Dispatch unit tests impl"

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      runner-label:
        required: true
        type: string
      timeout:
        required: false
        type: number
        default: 35
      os:
        required: false
        type: string
        default: "ubuntu-20.04"
  workflow_dispatch:
    inputs:
      arch:
        required: true
        type: choice
        options:
          - grayskull
          - wormhole_b0
          - blackhole
      runner-label:
        required: true
        type: choice
        options:
          - E150
          - N150
          - N300
          - BH
      timeout:
        required: false
        type: number
        default: 35
      os:
        required: false
        type: string
        default: "ubuntu-20.04"

jobs:
  unit-tests-slow-dispatch:
    name: ${{ inputs.arch }} ${{ inputs.runner-label }}
    runs-on:
      - ${{ inputs.runner-label }}
      - cloud-virtual-machine
      - in-service
    env:
      ARCH_NAME: ${{ inputs.arch }}
      LOGURU_LEVEL: INFO
    steps:
      - uses: tenstorrent/tt-metal/.github/actions/checkout-with-submodule-lfs@main
      - uses: ./.github/actions/prepare-metal-run
        with:
          arch: ${{ inputs.arch }}
      - name: Run pre/post regression tests
        timeout-minutes: ${{ inputs.timeout }}
        uses: ./.github/actions/docker-run
        with:
          docker_os_arch: ${{ inputs.os }}-amd64
          docker_password: ${{ secrets.GITHUB_TOKEN }}
          docker_opts: |
            -e ARCH_NAME=${{ inputs.arch}}
            -e TT_METAL_HOME=${{ github.workspace }}
            -e TT_METAL_SLOW_DISPATCH_MODE=1
            -e LD_LIBRARY_PATH=${{ github.workspace }}/build/lib
          install_wheel: true
          run_args: |
            ./tests/scripts/run_tests.sh --tt-arch ${{ inputs.arch }} --pipeline-type post_commit --dispatch-mode slow
      - uses: ./.github/actions/slack-report
        if: ${{ failure() }}
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          owner: U06CXU895AP # Michael Chiou
      - name: Generate system logs on failure
        uses: ./.github/actions/generate-system-logs
        if: ${{ failure() }}
