name: "[internal] C++ tests impl"

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      runner-label:
        required: true
        type: string
      timeout:
        required: false
        type: number
        default: 80
      os:
        required: false
        type: string
        default: "ubuntu-20.04"
  workflow_dispatch:
    inputs:
      arch:
        required: true
        type: choice
        options:
          - grayskull
          - wormhole_b0
          - blackhole
      runner-label:
        required: true
        type: choice
        options:
          - E150
          - N150
          - N300
          - BH
      timeout:
        required: false
        type: number
        default: 60
      os:
        required: false
        type: string
        default: "ubuntu-20.04"

jobs:
  models:
    strategy:
      # Do not fail-fast because we need to ensure all tests go to completion
      # so we try not to get hanging machines
      fail-fast: false
      matrix:
        test-group: [
          {name: C++, cmd: ./tests/scripts/run_cpp_unit_tests.sh},
          {name: ttnn cpp tests, cmd: ./build/test/ttnn/unit_tests_ttnn},
          {name: ttnn ccl cpp unit tests, cmd: ./build/test/ttnn/unit_tests_ttnn_ccl},
        ]
    name: ${{ matrix.test-group.name }} ${{ inputs.arch }} ${{ inputs.runner-label }}
    env:
      TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
      ARCH_NAME: ${{ inputs.arch }}
      LOGURU_LEVEL: INFO
      LD_LIBRARY_PATH: ${{ github.workspace }}/build/lib
    runs-on:
      - ${{ inputs.runner-label }}
      - cloud-virtual-machine
      - in-service
    steps:
      - uses: tenstorrent/tt-metal/.github/actions/checkout-with-submodule-lfs@main
      - name: Set up dynamic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - uses: ./.github/actions/prepare-metal-run
        with:
          arch: ${{ inputs.arch }}
      - name: ${{ matrix.test-group.name }} tests
        timeout-minutes: ${{ inputs.timeout }}
        uses: ./.github/actions/docker-run
        with:
          docker_os_arch: ${{ inputs.os }}-amd64
          docker_password: ${{ secrets.GITHUB_TOKEN }}
          install_wheel: true
          docker_opts: |
            -e TT_METAL_HOME=${{ github.workspace }}
            -e ARCH_NAME=${{ inputs.arch }}
            -e LD_LIBRARY_PATH=${{ github.workspace }}/build/lib
          run_args: |
            ${{ matrix.test-group.cmd }}
      - uses: ./.github/actions/slack-report
        if: ${{ failure() }}
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          owner: U06CXU895AP # Michael Chiou
      - name: Generate system logs on failure
        uses: ./.github/actions/generate-system-logs
        if: ${{ failure() }}
